// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Force new project configuration - clear any cached values
// Use environment variables for configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qkvmdrtfhpcvwvqjuyuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrdm1kcnRmaHBjdnd2cWp1eXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMjgyMTgsImV4cCI6MjA3NDgwNDIxOH0.DJeoI0LFeMArVs5s6DV2HP0kYnjWcIVLQEbiCQr97CE";

// Clear any cached auth data
if (typeof window !== 'undefined') {
  localStorage.removeItem('supabase.auth.token');
  localStorage.removeItem('supabase.auth.refresh_token');
  localStorage.removeItem('sb-yltbknkksjgtexluhtau-auth-token');
  localStorage.removeItem('sb-yltbknkksjgtexluhtau-auth-refresh-token');
  localStorage.removeItem('sb-qkvmdrtfhpcvwvqjuyuu-auth-token');
  localStorage.removeItem('sb-qkvmdrtfhpcvwvqjuyuu-auth-refresh-token');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Add better error handling
  global: {
    headers: {
      'x-client-info': 'aamodha-operations-portal'
    },
    fetch: async (url, options = {}) => {
      try {
        const response = await fetch(url, {
          ...options,
          // Add timeout
          signal: AbortSignal.timeout(30000), // 30 second timeout
        });
        return response;
      } catch (error: any) {
        // Enhanced error logging
        console.error('Supabase fetch error:', {
          url,
          error: error.message,
          type: error.name,
          cause: error.cause
        });
        
        // If it's a network error, provide helpful message
        if (error.name === 'AbortError' || error.message?.includes('Failed to fetch')) {
          throw new Error('Network error: Unable to connect to Supabase. Please check your internet connection and try again.');
        }
        
        throw error;
      }
    }
  }
});

// Helper function to handle Supabase errors with better messages
export const handleSupabaseError = (error: any): string => {
  if (!error) return 'An unknown error occurred';
  
  // Handle network/fetch errors
  if (error.message?.includes('Failed to fetch') || 
      error.message?.includes('Network error') ||
      error.message?.includes('network') ||
      error.name === 'TypeError') {
    return 'Network error: Unable to connect to Supabase. Please check your internet connection and try again. If the problem persists, the Supabase service may be temporarily unavailable.';
  }
  
  // Handle timeout errors
  if (error.message?.includes('timeout') || error.name === 'AbortError') {
    return 'Request timeout: The server took too long to respond. Please try again.';
  }
  
  // Handle network/SSL errors
  if (error.message?.includes('ERR_CERT_AUTHORITY_INVALID') || 
      error.message?.includes('certificate') ||
      error.message?.includes('SSL')) {
    return 'SSL certificate error. Please check your network connection or contact support.';
  }
  
  // Handle 400 Bad Request errors
  if (error.code === 'PGRST116' || error.message?.includes('400')) {
    return 'Invalid request. Please check your query parameters and try again.';
  }
  
  // Handle RLS (Row Level Security) errors
  if (error.code === '42501' || error.message?.includes('permission') || error.message?.includes('RLS')) {
    return 'Permission denied. Please check your access rights.';
  }
  
  // Return the error message if available
  return error.message || 'An error occurred while processing your request';
};