// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { log } from '@/lib/logger';

// Use environment variables for configuration (no hardcoded credentials)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? '';

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push('VITE_SUPABASE_ANON_KEY');
  throw new Error(
    `Missing required Supabase environment variables: ${missingVars.join(', ')}\n` +
    `Please set these variables in your .env file or environment configuration.`
  );
}

// Clear cached auth from OLD Supabase projects only (never the current project).
// This prevents mixing sessions when switching projects, while preserving session on normal refresh.
if (typeof window !== 'undefined') {
  const currentRef = SUPABASE_URL.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1] ?? '';
  const oldProjectRefs = ['yltbknkksjgtexluhtau', 'qkvmdrtfhpcvwvqjuyuu', 'ksfkgzlwgvwijjkaoaqq'].filter(
    (ref) => ref !== currentRef
  );
  oldProjectRefs.forEach((ref) => {
    localStorage.removeItem(`sb-${ref}-auth-token`);
    localStorage.removeItem(`sb-${ref}-auth-refresh-token`);
  });
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-client-info': 'aamodha-operations-portal',
    },
    fetch: async (url, options = {}) => {
      try {
        const response = await fetch(url, {
          ...options,
          signal: AbortSignal.timeout(30000), // 30-second timeout
        });
        return response;
      } catch (error: unknown) {
        const err = error as { message?: string; name?: string; cause?: unknown };

        log.error(
          err.message ?? 'Supabase fetch failed',
          {
            layer: 'Network',
            component: 'SupabaseClient',
            fn: 'customFetch',
            endpoint: typeof url === 'string' ? url.replace(SUPABASE_URL, '') : String(url),
            errorName: err.name,
            cause: err.cause,
          },
          error
        );

        if (err.name === 'AbortError' || err.message?.includes('Failed to fetch')) {
          throw new Error(
            'Network error: Unable to connect to Supabase. Please check your internet connection and try again.'
          );
        }

        throw error;
      }
    },
  },
});

// Helper function to handle Supabase errors with better messages
export const handleSupabaseError = (error: unknown): string => {
  if (!error) return 'An unknown error occurred';

  const errorObj = error as { message?: string; name?: string; code?: string };

  if (
    errorObj.message?.includes('Failed to fetch') ||
    errorObj.message?.includes('Network error') ||
    errorObj.message?.includes('network') ||
    errorObj.name === 'TypeError'
  ) {
    return 'Network error: Unable to connect to Supabase. Please check your internet connection and try again.';
  }

  if (errorObj.message?.includes('timeout') || errorObj.name === 'AbortError') {
    return 'Request timeout: The server took too long to respond. Please try again.';
  }

  if (
    errorObj.message?.includes('ERR_CERT_AUTHORITY_INVALID') ||
    errorObj.message?.includes('certificate') ||
    errorObj.message?.includes('SSL')
  ) {
    return 'SSL certificate error. Please check your network connection or contact support.';
  }

  if (errorObj.code === 'PGRST116' || errorObj.message?.includes('400')) {
    return 'Invalid request. Please check your query parameters and try again.';
  }

  if (
    errorObj.code === '42501' ||
    errorObj.message?.includes('permission') ||
    errorObj.message?.includes('RLS')
  ) {
    return 'Permission denied. Please check your access rights.';
  }

  return errorObj.message || 'An error occurred while processing your request';
};
